import networkx as nx
import matplotlib.pyplot as plt
G=nx.Graph()
G.add_node(1)
G.add_node(2)
G.add_node(3)
G.add_node(4)
G.add_node(5)
G.add_edge(1, 2)
G.add_edge(1, 6)
G.add_edge(3, 2)
G.add_edge(3, 4)
G.add_edge(5, 4)
#print(G.edges())
#print(G.nodes())
#nx.draw(G,with_labels=1)

Z=nx.Graph()
Z.add_node(1)
Z.add_node(2)
Z.add_node(3)
Z.add_node(4)
Z.add_node(5)
Z.add_node(6)
Z.add_edge(1, 2)
Z.add_edge(3, 2)
Z.add_edge(4, 2)
Z.add_edge(5, 2)
Z.add_edge(6, 2)
#nx.draw(Z,with_labels=1,node_color='g')
#print(Z.nodes())

#K=nx.complete_graph(25)
#nx.draw(K,with_labels=1,node_color='r')

M=nx.complete_graph(70)
pos=nx.circular_layout(M)
nx.draw(M,pos,with_labels=1,node_color='g')
print(M.order())
l=[2,2,2,1]
print(nx.is_graphical(l))